name: chat
channels:
  - defaults
dependencies:
  - pip:
    - playwright
    - python-dotenv
    - python-telegram-bot==20.0a6
    - requests
    - google-search-results
    - nest-asyncio==1.5.6
    - python-telegram-bot==20.0a6
